src/SonOfCodSeafood/Controllers/MemberListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using SonOfCodSeafood.Models;
using Microsoft.AspNetCore.Authorization;


namespace SonOfCodSeafood.Controllers
{
    public class MemberListController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        //public object UserManager { get; internal set; }
        public MemberListController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _db = db;
        }

        // GET: /<controller>/
        public IActionResult Entry()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Entry(Member newMember)
        {
            newMember.Role = "Admin";
            _db.Members.Add(newMember);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Index()
        {
                ViewBag.Members = _db.Members.ToList();
            return View();
        }
    }
}

src/SonOfCodSeafood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="~/css/styles.css">
        @*<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>*@
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="MainTitle">
                    <h1>Son Of Cod Seafood</h1>
                </div>
            </div>
            <section class="nav">
                <ul class="nav navbar-nav">
                    <li>@ViewBag.Home</li>
                    <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Our Products<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Fresh</a></li>
                            <li><a href="#">Processed</a></li>
                            <li><a href="#">Dried</a></li>
                        </ul>
                    </li>
                    <li class="active">@Html.ActionLink("Our Members", "Index", "MemberList")</li>
                    <li><a href="#">Newsletters</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </section>
           <hr />
            @RenderBody()
        </div>
    </body>
</html>